実装_在庫一覧画面(在庫一覧表示, 検索機能), 設計書修正(ログフォーマット)
yamato-mizoguchi/digital-ojt-development-cause-DroneInventorySystem pull request #17
Opened 2024-12-02 05:52 UTC by yamato-mizoguchi

## 概要

実装工程_在庫一覧画面の在庫一覧表示、検索機能およびログ設定のタスクが完了いたしました。
レビューをお願いいたします。

## 実装方針・詳細

・「個数」をString型で受け取り、検索時に内部でInteger型に変換する方法を取っているのは、Int型以外の入力値に対して、エラーメッセージを表示するためです。

・可読性が低い部分については都度リファクタリングしていきます。

2024-12-02 12:08 UTC, aoyagi96 requested changes
処理的には問題無さそうですが、PRのコメントにもあったように可読性、保守性を意識しリファクタリングを進めて頂けたらと思います。

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/StockListController.java
> +	@GetMapping("/admin/stockList/getStockNamesByCategoryId")
他に合わせてこのパスもUrlConstsから取った方が良いかもしれません。

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/StockListController.java
> +
```
// プルダウンに表示する前フォームでの入力情報（名称以外）をセット
model.addAttribute("inputtedValue", form);

// プルダウンに表示する分類をセット
model.addAttribute("categories", categoryInfoService.getCategoryInfoData());

// 画面表示用に在庫情報リストをセット
model.addAttribute("stockInfoList", stockInfoList);
```
この処理が何か所か出てくるので共通のメソッドにした方が良いでしょう

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/filter/LogSettingFilter.java
> +    String CLIENT = "client";
```suggestion
   private static final String CLIENT = "client";
```
定数ならこの方が良いのでは

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/filter/LogSettingFilter.java
> +//        try {
これは可読性が悪くなるので、コメントアウトしたコードは削除した方が良いです
（履歴はGithubで確認できるので）

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/resources/templates/admin/stockList/index.html
> +					$.ajax({
ajaxの利用は素晴らしいです！

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/validation/StockInfoFormValidatorImpl.java
> +			context.disableDefaultConstraintViolation();
ここの処理も重複してるので、メソッド化した方が良いですね

```
private void setErrorMessage(ConstraintValidatorContext context, String errorMessage) {
      context.disableDefaultConstraintViolation();
      context.buildConstraintViolationWithTemplate(errorMessage).addConstraintViolation();
}
```
のようなメソッドを作成し、

`setErrorMessage(context, ErrorMessage.ALL_FIELDS_EMPTY_ERROR_MESSAGE);`

みたいに呼び出す

2024-12-02 12:08 UTC, aoyagi96 commented on DroneInventorySystem/src/main/resources/templates/admin/stockList/index.html
> +						type="text">
type="number"で数値だけ入力できるようにした方が良いかも

2024-12-03 04:32 UTC, yamato-mizoguchi commented
ご確認ありがとうございます。
ご指摘いただいた内容にプラスして以下の点について修正いたしました。

・LogSettingFilter内で管理者IDを定数化
・html側で数値のみ入力に変更したことに合わせて、placeholderで期待する入力値を可視化

以上、ご確認よろしくお願いいたします。

2024-12-03 06:05 UTC, yamato-mizoguchi commented
Controller内の検索項目「名称」のプルダウンに表示する情報を入れる部分の処理に関して、メソッド内に入れるよう変更いたしました。

2024-12-03 09:50 UTC, aoyagi96 approved these changes
LGTM
すごく可読性が高まったと思います！

2024-12-03 09:56 UTC, yamato-mizoguchi commented
ご確認ありがとうございます。
二度手間になってしまい申し訳ございませんが、後ほどDTO用いたもので改めてレビュー依頼させていただきます。

2024-12-04 00:33 UTC, yamato-mizoguchi commented
DTOを用いたリファクタリングを行いました。
再度ご確認よろしくお願いいたします。

実装のポイント
・検索項目「個数」について、桁数と数値or文字列のバリデーション時に発生するエラーの区別のため、String型で取得してInteger型に変えてから検索を行っている関係で、サービスクラスに二つのメソッドが必要になりました。
・model.addAttributeでデータを渡すメソッドは、springMVCのベストプラクティスに倣ってコントローラー内に記述しています。

2024-12-04 01:08 UTC, yamato-mizoguchi commented
設計書の修正を行いました。
変更点：
・エラーメッセージ出力する入力値を変更
　　※個数は9桁以内で入力してください。　入力値「1234567891」→「int型の範囲外の値」

変更理由：
・桁数チェックの目的はint型範囲外の値をチェックするためで、厳密に桁数をチェックする目的ではありません。そのためユーザー視点で分かりやすい桁数を表向きの入力範囲としていますが、int型の範囲内であれば入力を受け付けるという仕様にいたしました。
　　

2024-12-04 11:53 UTC, aoyagi96 approved these changes
確認しました！
DTOの使い方もバッチリだと思います。
ナイスチャレンジです！

2024-12-04 11:53 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/service/StockInfoService.java
> +	public StockInfoDTO setStockInfoDTO(StockInfoForm form) {
DTOを追加することで、可動性がかなり良くなったと思います。
またデータの加工も柔軟になるのではないかと思います。
とても良い試みですね！

2024-12-05 04:35 UTC, yamato-mizoguchi commented
ご確認ありがとうございます。
マージし、在庫一覧画面はテストに入りたいと思います。

2024-12-05 05:08 UTC, merged