実装_在庫センター情報画面
yamato-mizoguchi/digital-ojt-development-cause-DroneInventorySystem pull request #19
Opened 2024-12-06 02:29 UTC by yamato-mizoguchi

## 概要

実装_在庫センター情報画面のPRです。

DBのエラー時の実装部分については、現在PR中の在庫一覧画面の実装方法で問題なければこちらにも反映させます。

2024-12-06 02:31 UTC, yamato-mizoguchi commented
実装_在庫センター情報画面（表示項目追加, 検索条件追加）のタスクが完了いたしました。
レビューをよろしくお願いいたします。

設計書については、エラーメッセージの仕様について修正しております。

2024-12-06 12:52 UTC, aoyagi96 requested changes
コメントをご確認ください。

2024-12-06 12:52 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	public void setView(Model model, CenterInfoDTO centerInfoDTO, CenterInfoForm form) {
共通化処理のメソッド化はナイスです。

2024-12-06 12:52 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/form/CenterInfoForm.java
> +	private String storageCapacityFrom;
IntegerではなくStringにしたのはなぜでしょう？

2024-12-06 12:52 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/form/CenterInfoForm.java
> +	private String storageCapacityFrom;
center_infoテーブルの「最大保管容量」と「現在保管容量」の型はINTでOKです。

2024-12-09 00:27 UTC, yamato-mizoguchi commented on DroneInventorySystem/src/main/java/com/digitalojt/web/form/CenterInfoForm.java
> +	private String storageCapacityFrom;
IntegerからStringにした理由として以下のようなものがあります。

・何も入力していない場合と、Integer型の範囲外の入力・文字の入力でエラーを分けられないと考えたため。（すべてnullで入るため）
例）fromに100,toにint型の範囲外の値を入れた場合、バリデーションを突破して100以上で検索出来てしまう。

・入力できる数値の上限や下限を変更できるようにするため。

2024-12-09 03:47 UTC, yamato-mizoguchi commented
【レビュー依頼】
実装_在庫センター情報画面（登録機能）のタスクが完了いたしました。
レビューをお願いいたします。

実装_在庫センター情報画面1のコミットで機能の大部分、2のコミットでDBで例外発生時の処理追加、3のコミットで付け忘れていた@Transactionalの追加を行っています。ばらついてしまってすみません。

実装のポイント：
新規登録では基本的にアノテーションを用いて入力チェックを行っています。
こちらの実装方法では設定した型に合致しない入力がされた場合、デフォルトのエラーメッセージとともにバリデーションエラーになるため、フォームクラスの「最大保管容量」と「現在保管容量」の型はInteger型で設定しています。

2024-12-09 23:25 UTC, aoyagi96 reviewed
細かい点ですが、コメントを確認ください。

2024-12-09 23:25 UTC, aoyagi96 commented on DroneInventorySystem/logs/dojt/2024-12-05_stockmng.log
> +（INFO）（2024/12/05 19:58:48.131）（IP:）（管理者ID:）（com.digitalojt.web.DroneInventorySystemApplication）（Starting DroneInventorySystemApplication using Java 17.0.12 with PID 1208 (C:\Documents\digital-ojt-de
logsは.gitignoreに追加してバージョン管理から外した方が良いかもしれません。

2024-12-09 23:25 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 初期表示
初期表示ではなく登録処理でしょうか

2024-12-09 23:25 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 初期表示
登録画面の初期表示ってことですかね。

2024-12-09 23:25 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 検索結果表示
登録処理でしょうか。

2024-12-09 23:25 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/form/CenterInfoEditForm.java
> +	@NotEmpty(message = "{"+ ErrorMessage.CENTER_NAME + ErrorMessage.FIELD_EMPTY + "}")
アノテーションによるバリデーションチェックは良いですね！

2024-12-10 03:24 UTC, yamato-mizoguchi commented on DroneInventorySystem/logs/dojt/2024-12-05_stockmng.log
> +（INFO）（2024/12/05 19:58:48.131）（IP:）（管理者ID:）（com.digitalojt.web.DroneInventorySystemApplication）（Starting DroneInventorySystemApplication using Java 17.0.12 with PID 1208 (C:\Documents\digital-ojt-de
承知しました。
logs以下はバージョン管理から外します。

2024-12-10 03:25 UTC, yamato-mizoguchi commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 初期表示
初期表示に関しては登録画面の初期表示という意味合いで書いていますが、伝わりにくいので変更いたします。

2024-12-10 03:25 UTC, yamato-mizoguchi commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 検索結果表示
修正いたします。

2024-12-10 03:38 UTC, yamato-mizoguchi commented
【レビュー依頼】実装_在庫センター情報画面（更新機能・削除機能）のタスクが完了いたしました。
また、併せて登録機能のレビュー指摘事項も修正いたしました。

レビューをよろしくお願いいたします。

2024-12-10 08:26 UTC, aoyagi96 reviewed
コメントをご確認ください。

2024-12-10 08:26 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	public String deleted(@PathVariable("centerId") Integer id, CenterInfoForm centerInfoForm, Model model) {
削除処理の操作ログが漏れてますかね。

2024-12-10 08:26 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/service/CenterInfoService.java
> +		    // 在庫情報が存在する場合、例外をスロー
例外のスローでセンターが使われているかチェックは良いと思います！

2024-12-10 08:39 UTC, yamato-mizoguchi commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	public String deleted(@PathVariable("centerId") Integer id, CenterInfoForm centerInfoForm, Model model) {
処理開始・完了・DB処理中の例外のロガーはサービスクラスに、在庫情報テーブルに存在するセンターを削除しようとした場合のロガーはExceptionControllerに置いております。

他にログが必要であるとのご指摘でしょうか。

2024-12-10 08:40 UTC, yamato-mizoguchi commented on DroneInventorySystem/src/main/java/com/digitalojt/web/form/CenterInfoEditForm.java
> +	@NotEmpty(message = "{"+ ErrorMessage.CENTER_NAME + ErrorMessage.FIELD_EMPTY + "}")
ありがとうございます！

2024-12-10 08:41 UTC, yamato-mizoguchi commented on DroneInventorySystem/src/main/java/com/digitalojt/web/service/CenterInfoService.java
> +		    // 在庫情報が存在する場合、例外をスロー
ありがとうございます！

2024-12-11 01:44 UTC, aoyagi96 commented on DroneInventorySystem/logs/dojt/2024-12-05_stockmng.log
> +（INFO）（2024/12/05 19:58:48.131）（IP:）（管理者ID:）（com.digitalojt.web.DroneInventorySystemApplication）（Starting DroneInventorySystemApplication using Java 17.0.12 with PID 1208 (C:\Documents\digital-ojt-de
確認しました。

2024-12-11 01:44 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 初期表示
確認しました。

2024-12-11 01:44 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	 * 検索結果表示
確認しました。

2024-12-11 01:45 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/controller/CenterInfoController.java
> +	public String deleted(@PathVariable("centerId") Integer id, CenterInfoForm centerInfoForm, Model model) {
なるほど！
失礼いたしました。であればOKです。

2024-12-11 01:46 UTC, aoyagi96 commented
指摘内容、全て確認できました。

2024-12-11 05:53 UTC, yamato-mizoguchi commented
在庫センター情報画面全体のリファクタリングと設計書修正を行いました。
また、削除済み情報に対する編集・削除画面への遷移を不可能にしました。（repositoryファイル内のクエリの編集）

2024-12-11 06:23 UTC, yamato-mizoguchi commented
在庫センター情報画面全体のリファクタリングと設計書修正を行いました。
また、削除済み情報に対する編集・削除画面への遷移を不可能にしました。（repositoryファイル内のクエリの編集）

2024-12-11 08:18 UTC, aoyagi96 approved these changes
LGTM
OKだと思います。

2024-12-11 08:21 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/form/CenterInfoForm.java
> +	private String storageCapacityFrom;
承知致しました。

2024-12-11 08:22 UTC, aoyagi96 commented
> 実装_在庫センター情報画面（表示項目追加, 検索条件追加）のタスクが完了いたしました。 レビューをよろしくお願いいたします。
> 
> 設計書については、エラーメッセージの仕様について修正しております。

承知致しました。

2024-12-12 08:35 UTC, merged